### ISSUE TITLE
Kindle 4 Silver - Battery discharging while being plugged

### ISSUE THREAD

**Issue by Sku4l** [sibbl/hass-lovelace-kindle-4#4]
Hi Sibbl,

Thanks again for the work.

I am eperiencing something I don't understand despite trying several things: My K4S is always plugged... but after about 24 hours running, it starts showing the "Low battery" image, and then it "dies" after some time.

I thought I damaged the battery connector, but it doesn't seem to be the case: It seems that while always plugged, the battery charges and after being charged, the kindle will somewhat stop using the power from the adapter and start using the battery. The charging led still displays "green" even though the battery depletes until it is completely depleted.

If I unplug the outlet from my wall electricity outlet for about 10 seconds, the led turns off and then if I reconnect it, the led goes back to orange again, then it will charge until green... and then we go all over again.

Is this something you are experiencing? Did I misunderstand some of of the parameters in the shell that I should adapt (maybe the BATTERYSLEEP? I don't really understand what this parameter is for

```
BATTERYALERT=15                         # if the battery level is equal to or below this threshold, a info will be displayed
BATTERYLOW=5                            # if the battery level is equal to or below this threshold, the "please charge" image will be shown and the device will sleep for a long time until it checks again (or boots up and starts the script again)
BATTERYSLEEP=3600                       # 1 day sleep time when Battery Level is equal or below the "BATTERYLOW" threshold, see above.
```

Thanks!

**Comment by sibbl** [comment]
Unfortunately I cannot reproduce it myself and can just recommend to play around with your setup. I'm also not sure how different the silver Kindle 4 is... is the charging LED green or yellow? If it's always green, perhaps try to wake your kindle and plug it back in if it's orange.

I can only guess that the Kindle maybe has some logic which turns off charging if it internally thinks it's at 100% (=green LED). I'm not sure how this logic behaves if the device is mostly sleeping...

`BATTERYSLEEP` means that the device will sleep for 3600 seconds if the battery is below 5% (which is one hour, not 1 day as mentioned in the comment though). It's meant to reduce the wake up time in order to save battery and give you time to plug in the device.

So unfortunately I can't do much but will keep the issue open. Maybe someone else has a device where it can be easily reproduced and fixed.

**Comment by Sku4l** [comment]
Thank you for the answer, i'll try investigating further.

I have an easy but dirty workaround which would be to have a connected plug that unplugs a minute every 24 hours, but maybe there is a software solution

**Comment by sibbl** [comment]
> I have an easy but dirty workaround which would be to have a connected plug that unplugs a minute every 24 hours, but maybe there is a software solution

Sounds very dirty and I'm pretty sure it's a software solution... 

Another idea what you could try: uncomment the logic which evaluates the current battery level so that it continues downloading and drawing the image. This would help us understand if the battery really does not charge (it would stop working then) or if only the battery level value is not properly read/updated (then it would continue working even though the battery level value prints zero).

**Comment by Sku4l** [comment]
So I got a second K4S to check the behavior and actually it is correctly handling the charging/discharging... So it seems very isolated to the original K4S.

I couldn't find a good answer to charge/discharge, so what I did is another dirty workaround:
I replaced the battery management and just added "reboot" and "exit" commands.

I guess that we can close the topic: it has nothing to do with this repository.

Thanks for the support

**Comment by marciogranzotto** [comment]
I'm having the same problem with my Silver Kindle 4... the light goes green and it stops charging. Then after a day or so, it just dies. Unplugging and plugging the USB cable changes the light to orange and starts charging again

**Comment by Sku4l** [comment]
Ok so I was not alone. I spent quite a significant time trying to find a solution or even just trying to understand where the problem comes from. I asked on the mobileread forums etc but no answer.

I am actually satisfied with the reboot workaround: I just replaced the battery management code with two commands : reboot and exit

So whenever the battery is low, the kindle reboots. It takes less than 2 minutes + 2 minutes to start the script... So not a big deal to miss 3 pictures.

I guess a cleaner workaround would be to be able to define a reboot time in the configuration file and say for example that it reboots at 4 am in the night, that way the whole workaround would be completely invisible if your battery manages to hold 24 hours.

Moreover, I had WiFi issues on the second kindle (not on the first...), I also replaced the WiFi recovery code with reboot and exit... And every thing is dirty but fine now haha

**Comment by marciogranzotto** [comment]
I'm having WiFi problems too.. Mine is getting stuck on `wlan network unavailable`. I found an issue on the script file that was never calling a reconnect. Fixed that on #5. Now it tries to reconnect but it doesn't connect for some reason.

**Comment by marciogranzotto** [comment]
ok, I solved my wifi problem disabling the `auto` file of `usbNetwork` and letting my kindle boot without `usb drive mode`. It reconnected to my Wi-Fi and then the homeassistant script worked 🤷‍♂️

**Comment by sibbl** [comment]
Interesting issue... I also wonder if the script stops some Linux services at the beginning, which might lead to this issue.

I'll try to investigate this as well with the 2 Kindle's I've got here, which also have slightly different behaviors although I've set them up 100% the same way (including the usbnetwork config). I imagine every Kindle's battery health is a bit different, which might also lead to different behaviors.

**Comment by sibbl** [comment]
I've opened a PR which I'm currently testing on two devices: #7 

Restarting powerd seems to fix the issue and I'm finding the best way to do this in a way which is gentle for the battery.

**Comment by Sku4l** [comment]
Thanks a lot, I have deployed it this morning and will report if it works (and logs also as I noticed you have added some details there)

**Comment by marciogranzotto** [comment]
Nice, just added the changes to my unit too. I'll report back if I have any other issues

**Comment by marciogranzotto** [comment]
> ok, I solved my wifi problem disabling the `auto` file of `usbNetwork` and letting my kindle boot without `usb drive mode`. It reconnected to my Wi-Fi and then the homeassistant script worked 🤷‍♂️

I was still having weird issues where it would just stop updating. Turns out that the `mnt/us` partition was out of space! Deleting all my books solved the issue.

**Comment by Pattern91** [comment]
Hey, i still have this issue. This is the part of my log file. It seems it realises that it is charging but with no current? Is this possible? I get this behaviour independent on the usb-charger... can anyone help?

> Mon Mar 14 18:26:52 UTC 2022: START NEW LOOP
> Mon Mar 14 18:26:52 UTC 2022: Set CPU scaling governer to powersave
> Mon Mar 14 18:26:52 UTC 2022: Set prevent screen saver to true
> Mon Mar 14 18:26:53 UTC 2022: Battery: isCharging=1 percentage=24% current=-3 mA
> Mon Mar 14 18:26:53 UTC 2022: Restarting powerd
> Mon Mar 14 18:26:55 UTC 2022: Remaining battery 24
> Mon Mar 14 18:26:55 UTC 2022: Enabling and checking wifi
> Mon Mar 14 18:26:55 UTC 2022: Connected to wifi
> Mon Mar 14 18:26:55 UTC 2022: Found default gateway 192.168.178.1
> Mon Mar 14 18:26:55 UTC 2022: Ping worked successfully
> Mon Mar 14 18:26:56 UTC 2022: Download result
> Mon Mar 14 18:26:56 UTC 2022: Screen saver image file updated
> Mon Mar 14 18:26:56 UTC 2022: Removed temporary files
> Mon Mar 14 18:27:06 UTC 2022: SUCCESS, will update again on 1647282476
> Mon Mar 14 18:28:07 UTC 2022: START NEW LOOP
> Mon Mar 14 18:28:08 UTC 2022: Set CPU scaling governer to powersave
> Mon Mar 14 18:28:08 UTC 2022: Set prevent screen saver to true
> Mon Mar 14 18:28:11 UTC 2022: Battery: isCharging=1 percentage=24% current=-3 mA
> Mon Mar 14 18:28:12 UTC 2022: Restarting powerd
> Mon Mar 14 18:28:15 UTC 2022: Remaining battery 24
> Mon Mar 14 18:28:15 UTC 2022: Enabling and checking wifi
> Mon Mar 14 18:28:16 UTC 2022: Waiting for wifi 1
> Mon Mar 14 18:28:17 UTC 2022: Waiting for wifi 2
> Mon Mar 14 18:28:20 UTC 2022: Waiting for wifi 3
> Mon Mar 14 18:28:24 UTC 2022: Waiting for wifi 4
